### PR TITLE
Approve notification function

### PR DESCRIPTION
**Pull request by SpookyKipper**
`approveNotification()` to prevent actions failing by "Important Notice, if you don't approve you will lose your account etc..."
**REQUIRES EXPLICT CALLING**

### CODE REVIEW

**Comment by 4yx** [comment]
This should've been handled in login, specifically https://github.com/GenerateApps/VPClient/blob/main/api-client.php#L194-L204. Did iFastNet change the error message? If so, I believe it should be updated there, or have approveNotification called from there but with the correct error message.

**Comment by 4yx** [comment]
Tomorrow, unless you want to have a look at it @SpookyKipper.

**Comment by SpookyKipper** [comment]
It actually does!
I didn't know that because I used a different Authentication Method (SmallHost's).

Anyways, will having an explicit function for it be cool (not removing it from Login)?

**Comment by 4yx** [comment]
Yeah, it's cool, and we could even update login to call that function instead of doing a curl call that does the same.

**Pull request merged**
